### ISSUE TITLE
Discourse installation fails for connection to geolite database

### ISSUE THREAD

**Issue by pallavipawar521** [bitnami/bitnami-docker-discourse#122] opened 2020-01-02 07:03 UTC
I am trying to install discourse using latest docker image on kubernetes. The installation fails with error "SocketError: Failed to open TCP connection to geolite.maxmind.com:443 (getaddrinfo: No address associated with hostname)" . Does bitnami support the solution provided here ? https://meta.discourse.org/t/upgrade-rebuilds-fail-due-to-maxmind-db-eol/137387/4

**Comment by rafariossaa** [comment] 2020-01-02 15:42
Hi @pallavipawar521 ,
  We are trying to find a fix for this issue. 
  We will come back to you as soon as possible.

**Comment by mmacfadden** [comment] 2020-01-05 14:17
This is a duplicate of #110

**Comment by juan131** [comment] 2020-01-07 10:38
Closing as it's a duplicate

**Closed by juan131** 2020-01-07 10:38 UTC

**Comment by nurchulis** [comment] 2020-04-04 19:26
Check This if you use bitnami discourse without yml setting
Its Work
https://community.bitnami.com/t/receiving-500-error-after-trying-to-install-a-plugin/72570
