### ISSUE TITLE
Fail to get start

### ISSUE THREAD

**Issue by bill2004158** [bitnami/bitnami-docker-discourse#34] opened 2017-11-13 02:16 UTC
Error executing 'postInstallation': ERROR:  extension "hstore" already exists

**Comment by alex12Douze** [comment] 2017-11-13 09:14
Hi,
I had the same issue, I fixed it by persisting the /bitnami folder of the main discourse docker.
I think that the first time you start the discourse against a fresh Postgres database it runs migrations script (and install extensions) and put a "marker" in the discourse container in /bitnami to remember that migration has already been done.
So the second time you run the container with the same volume, it won't try to install pg extensions, and the migration step will be shorter.
The /bitnami volume is mandatory.

**Comment by juan131** [comment] 2017-11-13 17:25
Hello @bill2004158 @alex12Douze the problem is that it's using the latest version of PostgreSQL (Discourse is not compatible with PostgreSQL 10.X and it's using the latest version in the `docker-compose.yml`). You need to edit the `docker-compose .yml` to use the version 9.6:

```
     image: 'bitnami/postgresql:9.6'
```

I already committed the changes so you should be able to use the new version of the `docker-compose.yml` now.

**Comment by bill2004158** [comment] 2017-11-18 04:03
hello @juan131 , I have tried 9.6, it seems I have got this error:

> Welcome to the Bitnami postgresql container
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
> Send us your feedback at containers@bitnami.com
> nami    INFO  Initializing postgresql
> postgre INFO 
> postgre INFO  ########################################################################
> postgre INFO   Installation parameters for postgresql:
> postgre INFO     Persisted data and properties have been restored.
> postgre INFO     Any input specified will not take effect.
> postgre INFO   (Passwords are not shown for security reasons)
> postgre INFO  ########################################################################
> postgre INFO 
> nami    INFO  postgresql successfully initialized
> INFO  ==> Starting postgresql... 
> nami    ERROR Unable to start com.bitnami.postgresql: pg_ctl: could not start server
> Examine the log output.
> 2017-11-18T03:39:45.073817787Z

**Comment by juan131** [comment] 2017-11-20 14:01
I am unable to reproduce that... Could you please remove all the containers and images (unless you have other containers in use) and try it again?

```
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -qf dangling=true)
docker rmi bitnami/postgresql
docker rmi bitnami/discourse
docker-compose up
```

**Comment by bill2004158** [comment] 2017-12-02 10:50
@juan131 it works now. thanks, I guess that is because i didn't delete old volume which cause start fail.

**Comment by juan131** [comment] 2017-12-04 09:14
Great! I proceed to close the issue! Please reopen it if you find any problem with PostgreSQL again.

**Closed by juan131** 2017-12-04 09:14 UTC

**Comment by rwatts3** [comment] 2018-01-26 23:50
still does not work for me even after removing the volumes and mapping the discourse volume locally.

**Comment by rwatts3** [comment] 2018-01-26 23:52
correction, docker really hangs on to stuff it's resolved now thank you

**Comment by juan131** [comment] 2018-01-29 13:41
Hi @rwatts3 

Great! We are glad that you were able to fix the issue.

**Comment by narun4sk** [comment] 2019-02-12 12:11
Same problem here... 

`PostgreSQL` prior to starting up the `Discourse` container:
```
discourse=# select version();
                                         version                                         
-----------------------------------------------------------------------------------------
 PostgreSQL 9.6.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.2.0) 8.2.0, 64-bit
(1 row)

discourse=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)
```

Now I start the `Discourse` and get the following log:
```
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
discour INFO  Configuring Discourse database...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at pgsql:5432
postgre INFO  PostgreSQL server listening and working at pgsql:5432
discour INFO  Enabling PostgreSQL plugins for Discourse...
Error executing 'postInstallation': ERROR:  extension "hstore" already exists
```

`PostgreSQL` afterwards looks like the following:
```
discourse=# \dx
                                    List of installed extensions
  Name   | Version |   Schema   |                            Description                            
---------+---------+------------+-------------------------------------------------------------------
 hstore  | 1.4     | public     | data type for storing sets of (key, value) pairs
 pg_trgm | 1.3     | public     | text similarity measurement and index searching based on trigrams
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)
```

So it seems that `Discourse` somehow creates the `hstore` extension, but then fails to detect what it has done... Any ideas?

**Comment by juan131** [comment] 2019-02-13 08:42
Hi @narun4sk 

It looks like you're starting Discourse with a database that was already populated. 

When you start Discourse for the first time, it creates a flag in the persistent volume so it detects it's being initialised in future "starts" and it skips the initialisation. This way, we avoid re-populating a database twice and problems like the one you faced.

It looks like you're starting Discourse without the persistence volume containing the flag and it considers it needs to populate the database. However, it looks like your PostgreSQL database is already populated and, therefore, the issue.

**Comment by narun4sk** [comment] 2019-02-14 23:18
Thanks @juan131,

It turned out that it was a general `Kubernetes` *single-node-cluster* (not `minikube`) problem, as I had running `PosgreSQL` service with the same name in the other namespace. After some trial and error I've figured out right parameters by looking to your [test.yaml](https://github.com/bitnami/bitnami-docker-discourse/blob/master/test.yaml).

I wish `Kubernetes` instructions were better managed, as I've found env. variables like `POSTGRESQL_CLIENT_*` which are not documented anywhere and it's not clear whether they are obsolete or in the alpha state?

I've split `test.yaml` into the separate manifest files and I can PR if you would like add more support for `k8s`?

**Comment by juan131** [comment] 2019-02-15 09:13
Hi @narun4sk 

Ideally we'll create a Helm chart for Discourse in the future (as we did for other Bitnami containers, see https://github.com/bitnami/charts) but we didn't have time to work on Discourse chart yet.

Regarding PRs, your contribution is very welcome. Feel free to open a PR and we'll take a look!

**Comment by narun4sk** [comment] 2019-02-15 17:31
Hi @juan131,

Done, please take a look to #69.

**Comment by juan131** [comment] 2019-02-18 09:08
Great! Taking a look!
